#!/bin/sh

PIDFILE="${PIDFILE:-/var/run/lf_updated.pid}"
PID=$$

LFUSER="${LFUSER:-lf}"
DBHOST="${DBHOST:-localhost}"
DBNAME="${DBNAME:-liquid_feedback}"
DBUSER="${DBUSER:-liquid_feedback}"
DBPASS="${DBPASS:-liquid}"

if [ -e "/config/lf_update" ]; then
  source /config/lf_update
fi

if [ -f "${PIDFILE}" ] && kill -CONT $( cat "${PIDFILE}" ); then
  echo "lf_updated is already running."
  exit 1
fi

echo "${PID}" > "${PIDFILE}"

if [ "$EUID" -eq 0 ]; then
  run () {
    su -s bash ${LFUSER} -c "$1"
  }
else
  run () {
    bash -c "$1"
  }
fi


while true; do
  run "nice /opt/lf/bin/lf_update host=${DBHOST} dbname=${DBNAME} user=${DBUSER} password=${DBPASS}"
  run "nice /opt/lf/bin/lf_update_issue_order host=${DBHOST} dbname=${DBNAME} user=${DBUSER} password=${DBPASS}"
  run "nice /opt/lf/bin/lf_update_suggestion_order host=${DBHOST} dbname=${DBNAME} user=${DBUSER} password=${DBPASS}"
  sleep 5
done
